//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        public Ambiente()
        {
            this.Salas = new HashSet<Salas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string desclipcion { get; set; }
    
        public virtual ICollection<Salas> Salas { get; set; }
    }
}
