//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Comidas = new HashSet<Comidas>();
        }
    
        public int id_categoria { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int nit { get; set; }
        public int fotoid { get; set; }
    
        public virtual ICollection<Comidas> Comidas { get; set; }
        public virtual Foto Foto { get; set; }
        public virtual Restaurantes Restaurantes { get; set; }
    }
}
