//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comidas
    {
        public int id_comida { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
        public int Idprecio { get; set; }
        public int id_foto { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Foto Foto { get; set; }
        public virtual Precios Precios { get; set; }
    }
}
