//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles
    {
        public int id_detalle { get; set; }
        public int id_comida { get; set; }
        public decimal valor { get; set; }
        public short cantidad { get; set; }
        public int id_pedido { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
