//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesas
    {
        public Mesas()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int id_mesa { get; set; }
        public string nombre { get; set; }
        public string sillas { get; set; }
        public string tipo { get; set; }
        public int id_sala { get; set; }
        public int id_foto { get; set; }
    
        public virtual Foto Foto { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual Salas Salas { get; set; }
    }
}
