//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public Pedidos()
        {
            this.Detalles = new HashSet<Detalles>();
        }
    
        public int id_pedido { get; set; }
        public int id_servicio { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal iva { get; set; }
        public decimal total { get; set; }
        public decimal subtotal { get; set; }
        public int nit { get; set; }
        public int cedula { get; set; }
    
        public virtual ICollection<Detalles> Detalles { get; set; }
        public virtual Restaurantes Restaurantes { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual User User { get; set; }
    }
}
