//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id_reserva { get; set; }
        public int id_sala { get; set; }
        public int id_mesa { get; set; }
        public System.DateTime facha { get; set; }
        public string estado { get; set; }
        public int cedula { get; set; }
        public int nit { get; set; }
    
        public virtual Mesas Mesas { get; set; }
        public virtual Restaurantes Restaurantes { get; set; }
        public virtual Salas Salas { get; set; }
        public virtual User User { get; set; }
    }
}
