//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        public Zona()
        {
            this.Restaurantes = new HashSet<Restaurantes>();
        }
    
        public int id_zona { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Restaurantes> Restaurantes { get; set; }
    }
}
